/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaConsulta.java
 *
 * Created on Nov 30, 2011, 11:57:29 AM
 */
package Visao;

/**
 *
 * @author Gerson
 */
public class TelaConsulta extends javax.swing.JFrame {

    /** Creates new form TelaConsulta */
    public TelaConsulta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        deslogarMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();
        pacienteMenu = new javax.swing.JMenu();
        historicoMenuItem = new javax.swing.JMenuItem();
        consultaMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeMenu.setMnemonic('f');
        homeMenu.setText("Home");

        deslogarMenuItem.setMnemonic('o');
        deslogarMenuItem.setText("Deslogar");
        homeMenu.add(deslogarMenuItem);

        sairMenuItem.setMnemonic('s');
        sairMenuItem.setText("Sair");
        homeMenu.add(sairMenuItem);

        menuBar.add(homeMenu);

        pacienteMenu.setMnemonic('e');
        pacienteMenu.setText("Paciente");

        historicoMenuItem.setMnemonic('t');
        historicoMenuItem.setText("Historico");
        pacienteMenu.add(historicoMenuItem);

        menuBar.add(pacienteMenu);

        consultaMenu.setMnemonic('h');
        consultaMenu.setText("Consulta");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Solicitar Exame");
        consultaMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Gerar Receita");
        consultaMenu.add(aboutMenuItem);

        jMenuItem1.setText("Gerar Atestado");
        consultaMenu.add(jMenuItem1);

        menuBar.add(consultaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaConsulta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu consultaMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem deslogarMenuItem;
    private javax.swing.JMenuItem historicoMenuItem;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu pacienteMenu;
    private javax.swing.JMenuItem sairMenuItem;
    // End of variables declaration//GEN-END:variables
}
